//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Calificacion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacione
    {
        public int CalificacionID { get; set; }
        public int EstudianteID { get; set; }
        public int MateriaID { get; set; }
        public decimal Calificacion1 { get; set; }
        public decimal Calificacion2 { get; set; }
        public decimal Calificacion3 { get; set; }
        public decimal Calificacion4 { get; set; }
        public decimal Examen { get; set; }
        public decimal Total { get; set; }
        public string Clasificacion { get; set; }
        public string Estado { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
